name: .NET

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Publish (Release)'
      shell: pwsh
      run: |
        $version = (Get-Content "version.txt")
        Publish-Module -Path .\zxsh\ -NuGetApiKey ${{ secrets.POWERSHELL_GALLERY_API_KEY }}
        