name: .NET

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Build (Release)'
      shell: pwsh
      run: |
        $version = (Get-Content "version.txt")
        ls -R
        echo $version
        Get-PSRepository
        # Publish-Module -Name zxsh -NuGetApiKey ${{ secrets.POWERSHELL_GALLERY_API_KEY }} -RequiredVersion $version -Path './zxsh'