name: .NET

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Build (Release)'
      shell: pwsh
      run: |
        $apiKey = (Get-Content "version.txt")
        Publish-Module -Name zxsh -NuGetApiKey ${{ secrets.POWERSHELL_GALLERY_API_KEY }} -RequiredVersion $apiKey